import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    JWT_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    SMS_PROVIDER: z.ZodDefault<z.ZodEnum<["mock", "twilio"]>>;
    TWILIO_ACCOUNT_SID: z.ZodOptional<z.ZodString>;
    TWILIO_AUTH_TOKEN: z.ZodOptional<z.ZodString>;
    TWILIO_FROM_NUMBER: z.ZodOptional<z.ZodString>;
    STORAGE_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "s3"]>>;
    AWS_REGION: z.ZodDefault<z.ZodString>;
    AWS_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    AWS_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    AWS_S3_BUCKET: z.ZodDefault<z.ZodString>;
    STORAGE_LOCAL_PATH: z.ZodDefault<z.ZodString>;
    PAYMENT_PROVIDER: z.ZodDefault<z.ZodEnum<["mock", "razorpay"]>>;
    RAZORPAY_KEY_ID: z.ZodOptional<z.ZodString>;
    RAZORPAY_KEY_SECRET: z.ZodOptional<z.ZodString>;
    MAPS_PROVIDER: z.ZodDefault<z.ZodEnum<["mock", "google", "mapbox"]>>;
    GOOGLE_MAPS_API_KEY: z.ZodOptional<z.ZodString>;
    MAPBOX_TOKEN: z.ZodOptional<z.ZodString>;
    PUSH_PROVIDER: z.ZodDefault<z.ZodEnum<["mock", "fcm"]>>;
    FCM_SERVER_KEY: z.ZodOptional<z.ZodString>;
    LLM_PROVIDER: z.ZodDefault<z.ZodEnum<["mock", "openai", "anthropic"]>>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodOptional<z.ZodString>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["mock", "sendgrid"]>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    FROM_EMAIL: z.ZodDefault<z.ZodString>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    API_URL: z.ZodDefault<z.ZodString>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    SMS_PROVIDER: "mock" | "twilio";
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    STORAGE_PROVIDER: "local" | "s3";
    AWS_REGION: string;
    AWS_S3_BUCKET: string;
    STORAGE_LOCAL_PATH: string;
    PAYMENT_PROVIDER: "mock" | "razorpay";
    MAPS_PROVIDER: "mock" | "google" | "mapbox";
    PUSH_PROVIDER: "mock" | "fcm";
    LLM_PROVIDER: "mock" | "openai" | "anthropic";
    EMAIL_PROVIDER: "mock" | "sendgrid";
    FROM_EMAIL: string;
    API_PORT: number;
    API_URL: string;
    CORS_ORIGINS: string;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_FROM_NUMBER?: string | undefined;
    AWS_ACCESS_KEY_ID?: string | undefined;
    AWS_SECRET_ACCESS_KEY?: string | undefined;
    RAZORPAY_KEY_ID?: string | undefined;
    RAZORPAY_KEY_SECRET?: string | undefined;
    GOOGLE_MAPS_API_KEY?: string | undefined;
    MAPBOX_TOKEN?: string | undefined;
    FCM_SERVER_KEY?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    SENDGRID_API_KEY?: string | undefined;
}, {
    JWT_SECRET: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_REFRESH_SECRET: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    SMS_PROVIDER?: "mock" | "twilio" | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_FROM_NUMBER?: string | undefined;
    STORAGE_PROVIDER?: "local" | "s3" | undefined;
    AWS_REGION?: string | undefined;
    AWS_ACCESS_KEY_ID?: string | undefined;
    AWS_SECRET_ACCESS_KEY?: string | undefined;
    AWS_S3_BUCKET?: string | undefined;
    STORAGE_LOCAL_PATH?: string | undefined;
    PAYMENT_PROVIDER?: "mock" | "razorpay" | undefined;
    RAZORPAY_KEY_ID?: string | undefined;
    RAZORPAY_KEY_SECRET?: string | undefined;
    MAPS_PROVIDER?: "mock" | "google" | "mapbox" | undefined;
    GOOGLE_MAPS_API_KEY?: string | undefined;
    MAPBOX_TOKEN?: string | undefined;
    PUSH_PROVIDER?: "mock" | "fcm" | undefined;
    FCM_SERVER_KEY?: string | undefined;
    LLM_PROVIDER?: "mock" | "openai" | "anthropic" | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    EMAIL_PROVIDER?: "mock" | "sendgrid" | undefined;
    SENDGRID_API_KEY?: string | undefined;
    FROM_EMAIL?: string | undefined;
    API_PORT?: number | undefined;
    API_URL?: string | undefined;
    CORS_ORIGINS?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function getEnv(): Env;
export declare const BUSINESS_CONFIG: {
    readonly FREE_CANCELLATION_HOURS: 4;
    readonly PLATFORM_COMMISSION_RATE: 0.2;
    readonly MIN_WALK_RADIUS_KM: 1;
    readonly MAX_WALK_RADIUS_KM: 15;
    readonly WALK_REQUEST_EXPIRY_SECONDS: 45;
    readonly MAX_WALK_REQUEST_RETRIES: 3;
    readonly OTP_EXPIRY_MINUTES: 10;
    readonly OTP_LENGTH: 6;
    readonly MAX_PETS_PER_CUSTOMER: 10;
    readonly MAX_ADDRESSES_PER_CUSTOMER: 5;
    readonly MAX_PHOTOS_PER_JOB: 10;
    readonly BOOKING_CONFIRMATION_WINDOW_MINUTES: 30;
};
export {};
//# sourceMappingURL=index.d.ts.map